bbox_model_weight: 'yolo12x.pt'
bbox_classes: [0]

outline_model_weight: 'facebook/sam2-hiera-large' # segment anything2

segmentator_model_version: '1b'
segmentator_model_weight: 'sapiens.pt2'

pose_estimator_model_weight: yolo11x-pose.pt